version: 2.0

jobs:
  deploy:
    machine:
        enabled: true
    working_directory: /home/tricon/circlecli/circlecidemo
    steps:
      - run:
          name: Deployment Master to Heroku
          command: 
            ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy